# https://files.minecraftforge.net/net/minecraftforge/forge/
modLoader = "javafml"
loaderVersion = "[38,)"
license = "GPL-3"
issueTrackerURL="https://github.com/p0t4t0sandwich/BeeNameGenerator/issues"

[[mods]]
modId = "beenamegenerator"
version = "${file.jarVersion}"
displayName = "BeeNameGenerator"
updateJSONURL="https://raw.githubusercontent.com/p0t4t0sandwich/BeeNameGenerator/main/forgeUpdates.json"
displayURL="https://github.com/p0t4t0sandwich/BeeNameGenerator"
logoFile= "../BeeNameGenerator.png"
credits="p0t4t0sandwich"
authors="p0t4t0sandwich"
displayTest="IGNORE_SERVER_VERSION"
description = '''
A plugin that implements the bee-name-generator API to generate names for bees.
'''

# Forge Dependency
[[dependencies.beenamegenerator]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

# Minecraft Dependency
[[dependencies.beenamegenerator]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.19)"
ordering = "NONE"
side = "BOTH"

# LuckPerms Dependency
[[dependencies.beenamegenerator]]
modId = "luckperms"
mandatory = false
versionRange = "[5.3.0,)"
ordering = "NONE"
side = "SERVER"

# TaterLib Dependency
[[dependencies.beenamegenerator]]
modId = "taterlib"
mandatory = true
versionRange = "[1.0.0,)"
ordering = "NONE"
side = "SERVER"
