name: '${project_name}'
version: '${version}'
author: '${authors}'
description: '${project_description}'
website: '${homepage_url}'
main: '${group_id}.${project_id}.platforms.BukkitPlugin'
depend: [ TaterLib ]
depends: [ TaterLib ]
softdepends: [ ]
folia-supported: true
commands:
  bng:
    description: "A command that generates a name for a bee."
    usage: /bng <command> [args]
    permission: bng.command
