name: BeeNameGenerator
version: '${version}'
author: p0t4t0sandwich
description: A plugin that implements the bee-name-generator API to generate names for bees.
main: dev.neuralnexus.beenamegenerator.bukkit.BukkitBNGPlugin
depend: [TaterLib]
softdepend: [LuckPerms]
folia-supported: true
commands:
  bng:
    description: "A command that generates a name for a bee."
    usage: /bng <command> [args]
    permission: bng.command
