---
version: 1

api:
  # URL for the Bee Name Generator API
  base_url: "https://api.sperrer.ca/api/v1/bee-name-generator"

  # Auth Token for the Bee Name Generator API
  auth_token: "YOUR_AUTH_TOKEN"

naming:
  radius: 10
  payment_item: "minecraft:name_tag"
